### ISSUE TITLE
Use for-await-of here?

### ISSUE THREAD

**Issue by joostf** [maanlamp/web-app-from-scratch-18-19#1]
https://github.com/maanlamp/web-app-from-scratch-18-19/blob/fe777c9faab1fdeb8759e46040e016fb50d9bc01/week1/public/js/app.js#L23

https://flaviocopes.com/es2018/#asynchronous-iteration

**Comment by Razpudding** [comment]
Well spotted Joost! In addition to that, it might not even be necessary to wait for each fetch.
@maanlamp the current version of the code forces each fetch to be finished before the next is fired off,  it looks like that's not needed here. Try to think of a structure where the requests are fired synchronously but the total result is awaited upon. With promises, you can use Promise.all.
Good effort btw 👍

**Comment by maanlamp** [comment]
@joostf I know about for-await-of, but that wouldn't quite do what I want to be done without writing a custom iterator (iterator.next() would have to check if the total result count has been reached yet), which I don't want to 😄. I have recently decided I don't want to write loops ever again (if I can avoid them anyway) – I thought this was a perfect opportunity to skip one. I've used a combination of asynchronous maps to get the same result.

@Razpudding As for concurrency, the API I'm using is quite strict. It allows at most ~50 requests a second, but only if you somehow verify yourself to be "a good citizen and be smart about using the Web Service" (their words). This means I have to wait at least 20ms after each request, or 1s after every 50 requests. Therefore I simply cannot fire them all off at once. Besides the minimum 20ms timeout, I cannot for the life of me figure out how to verify that I'm a "good citizen", because I get throttled every time. I don't wait for every fetch anymore.

**_However_**
I did re-write the function to be more elegant and functional (quite literally, it didn't _actually_ work before 😛).

https://github.com/maanlamp/web-app-from-scratch-18-19/commit/45fbfc15fe7a650c3ec71d060f4388bf36dd0e9a#diff-ff2171ff13ac391b5c7cd6fc8b8675deR26

The only problem I have now is that I still have to use _Promise_.**all**() to wait for all fetches to complete. Surely there must be a way to "stream" promise resolvements (i.e. run a function everytime a promise resolves in an array)?

**Comment by joostf** [comment]
Fair enough; I like your functional approach, however I can imagine the loop is heavily optimized and should perform better?! 

Maybe you can write a recursive function that races all te promises? I'm not sure if this is very sensible, but it sounds like fun 🤪

**Comment by maanlamp** [comment]
Micro-optimalisations, like choosing a certain kind of loop over another -- because it's (supposedly) faster -- is not really a concern of mine. I would much rather just code something that works, and trust that the interpreter will fix my slowness. After all, if I'm smart enough to now it can be optmised, the parser will have already done that for me :).

["Performance matters... but only when it matters."](https://www.youtube.com/watch?v=eKuHlSZKlWM)  - Jake archibald, developer advocate for Google Chrome

I'm going to close this issue because the original while loop isn't in the code anymore, and the issue itself is resolved. Another issue will be opened for the _"promise streaming"_ I talked about.

See #7.
