### ISSUE TITLE
One module for all + auto defer

### ISSUE THREAD

**Issue by folkertjan** [maanlamp/web-app-from-scratch-18-19#5]
You only have to load `<script src="./public/js/app.js" type="module"></script> ` since making it a type module will auto detect import dependencies at the moment they are needed.
If preloading is what you are after, there's a [different attribute for that](https://developers.google.com/web/fundamentals/primers/modules#preload).

Furthermore, you could actually put a module script in the head since it automatically defers. (although that makes placement a preference, really)
[source](https://developers.google.com/web/fundamentals/primers/modules#defer)
https://github.com/maanlamp/web-app-from-scratch-18-19/blob/0c03a74d23d4ec020e722d03ec23004520ab3787/week1/index.html#L16-L18

**Comment by maanlamp** [comment]
The overuse of `type=module` is due to a quick regex that just "modularised" every script tag in my HTML at some point. You're right, not needed.

As for the automatic deferring, I had no idea. That's really :cool:. I can finally put script tags where they belong: in the head!

Fixed in https://github.com/maanlamp/web-app-from-scratch-18-19/commit/08f40f8deb5045f7ab97b7dc5776b6829b014778#diff-8adc7e6ea5a532da4a89e7e910127f2eR8

Thank you!
